[profile.default]
src = "src"
out = "out"
test = "test"
libs = ["lib"]

remappings = [
    '@chainlink/=lib/chainlink-brownie-contracts/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    
]

[rpc_endpoints]
sepolia = { url = "${SEPOLIA_RPC_URL}" }
